hostID = "0x0000000000000000000000000000000000000001"
hostAddress = "127.0.0.1:10000"
address = "127.0.0.1:11000"
nodeType = "sequencer"
l1ChainID = 1377
obscuroChainID = 777
willAttest = false
validateL1Blocks = false
managementContractAddress = "0x0000000000000000000000000000000000000000"
logLevel = 3
logPath = "enclave_logs.txt"
useInMemoryDb = true
sequencerID = "0x0000000000000000000000000000000000000000"
obscuroGenesis = ""