hostID = "0x0000000000000000000000000000000000000000"
address = "127.0.0.1:11000"
l1ChainID = 1377
obscuroChainID = 777
willAttest = false
validateL1Blocks = false
speculativeExecution = false
managementContractAddress = "0x0000000000000000000000000000000000000000"
erc20ContractAddresses = []
writeToLogs = false
logPath = "enclave_logs.txt"
useInMemoryDb = true