# The node-launcher environment is

network:
   GenesisJSON: "{}"
   gas:
      minGasPrice: +1
   sequencer:
      p2pAddress: sequencer-host:15000
host:
   l1:
      wsURL: ws://eth2network:9000
enclave:
   db:
      useInMemory: false