# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-UK"
title: "Obscuro"
# subtitle: "Privacy matters."
description: "Obscuro is an Ethereum-compatible confidential smart contract L2 network."
url: "https://obscu.ro"
name: "Obscuro"
repository: "obscuronet/obscuro.github.io"
search: true
# logo: "/assets/images/obscuro-small_88x88.png"

# Outputting
# permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jekyll-relative-links
  
titles_from_headings:
  strip_title: true
  
atom_feed:
  hide: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "pages"
      layout: single
      classes: wide
      author_profile: true
      strip_title: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/obscuronet"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/obscuronet"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/7pkKv2Tyfn"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XL6VWGQK1P"

theme: jekyll-theme-slate