# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-UK"
title: "Obscuro"
description: "Obscuro is an Ethereum-compatible confidential smart contract L2 network."
url: "https://obscu.ro"
name: "Obscuro"
repository: "obscuronet/obscuro.github.io"

# Breadcrumb Settings
breadcrumbs: true
breadcrumb_home_label: "Home"
breadcrumb_seperator: ">"

# Search Settings
search: true
search_provider: lunr
search_full_content: true
lunr:
  search_within_pages: true

# Collections of docs and posts
collections:
  docs: # must have identically named folder in directory structure with preceding underscore, i.e. _docs
    permalink: /:path/
    output: true
  posts:
    permalink: /:year/:title/
    output: true

defaults:
  # _docs
  - scope:
      path: "_docs" # folder name where docs md files are kept
      type: docs
    values:
      sidebar:
        nav: sidebar-list # has to match the name of the sidebar in navigation.yml
      layout: single
      classes: wide
      strip_title: true
  # _posts
  - scope:
      path: "_posts" # folder name where blog post files are kept
      type: posts
    values:
      sidebar:
        nav: sidebar-list # has to match the name of the sidebar in navigation.yml
      layout: single
  # all other pages including landing page need to be listed to have correct layout applied
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: sidebar-list # has to match the name of the sidebar in navigation.yml
      layout: single
      classes: wide
      strip_title: true

# Outputting
paginate: 5 # amount of posts to show
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-archives

titles_from_headings:
  strip_title: true
  collections: true
  
atom_feed:
  hide: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/obscuronet"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/obscuronet"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/7pkKv2Tyfn"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XL6VWGQK1P"

theme: jekyll-theme-slate