id = ""
isGenesis = true
nodeType = "aggregator"
gossipRoundDuration = 777
hasClientRPCHTTP = true
clientRPCPortHTTP = 13000
HasClientRPCWebsockets = true
ClientRPCPortWS = 13001
ClientRPCHost = "127.0.0.1"
ClientRPCTimeout = 10
EnclaveRPCAddress = "127.0.0.1:11000"
EnclaveRPCTimeout = 10
P2PBindAddress = "0.0.0.0:10000"
P2PPublicAddress = "127.0.0.1:10000"
L1NodeHost = "127.0.0.1"
L1NodeWebsocketPort = 8546
L1RPCTimeout = 15
RollupContractAddress = ""
LogLevel = 3
LogPath = ""
PrivateKeyString = "0000000000000000000000000000000000000000000000000000000000000001"
L1ChainID = 1337
ObscuroChainID = 777
ProfilerEnabled = false