name: Auto Assign to Project

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  # issue_comment:
  #  types: [created]
# env:
  # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to Obscuro project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/obscuronet/projects/1'

    - name: Assign issues and pull requests with `epic` label to Obscuro project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'epic') ||
        contains(github.event.pull_request.labels.*.name, 'epic')
      with:
        project: 'https://github.com/orgs/obscuronet/projects/1'
        column_name: 'To Do'
